modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="${modLicense}"
[[mods]]
    modId="${modId}"
    version="${modVersion}"
    displayName="${modName}"
    credits="${modCredits}"
    authors="${modAuthors}"
    description='''${modDesc}'''
    logoFile = "ecr.png"
[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="hollowcore"
    mandatory=true
    versionRange="[${hcVersion},)"
    ordering="NONE"
    side="BOTH"
